### ISSUE TITLE
Create Key Vault Error

### ISSUE THREAD

**Issue by moto-geek** [Azure/fedramp-iaas-webapp#59]
First I got error for using **'USGov Virginia'** then change this in the script to use the suggested **'usgovvirginia'**

Now getting: 

**No registered resource provider found for location 'usgovvirginia' and API version '2018-02-14-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.**

Can't get passed this error, any suggestions or updates? I do have a Govt Azure Subscription or how to change the Azure API verision used?

**Comment by jomolesk** [comment]
Can you provide any additional context for when you're encountering this error? Please check that the Microsoft.KeyVault resource provider is registered in your Azure Gov subscription. You can do this through the Azure portal under Cost Management + Billing > Subscriptions > Resource providers:
![rps](https://user-images.githubusercontent.com/23081194/40196814-a2961bd8-59df-11e8-9fad-0c69ac9c3bc5.png)

**Comment by moto-geek** [comment]
Was not, registered and trying again..

**Comment by moto-geek** [comment]
I did turn on Microsoft.KeyVault, now showing "registered" unfortunately the same error below.  This error occurs running the predeployment script "Orchestration_InitialSetup.ps1" when [Key Vault Resource] name is create. Then it fails with the below error in Powershell.  

![untitled-1](https://user-images.githubusercontent.com/7527202/40202367-fa362bcc-59de-11e8-8463-efed4d97a5d8.jpg)

Module Version Reference In Powershell:

Script     5.0.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertificate, Stop-AzureKeyVaultCertificateOperation, Get-AzureKeyVaultCertificateOperation...}

I'm going to try Import-Module -Name AzureRM older version

 for an API version it's asking for in the error. That's the only thing I can see so far that's an obvious thing to try next. I am going to have to determine somehow where version number matches the dates supplied. :(

**No registered resource provider found for location 'USGov Virginia' and API version '2018-02-14-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.
An error has occurred in the pre-deployment orchestration setup. Please review any error messages before attempting a re-deployment.**

**Comment by jomolesk** [comment]
Please let me know if that approach is successful. It looks like the RP in Azure Gov does not support the 2018-02-14-preview API version.
![image](https://user-images.githubusercontent.com/23081194/40202882-6eecd846-59f1-11e8-83b4-3e73d49373ab.png)

**Comment by moto-geek** [comment]
Thanks for the response jomolesk.. I ran this and got the following response. 

PS C:\> ((Get-AzureRmResourceProvider -ProviderNamespace Microsoft.KeyVault).ResourcTypes | Where-Object ResourceTypeNam
e -eq vaults).ApiVersions
>> 2016-10-01
>> 2015-06-01
**2005
2008**

Not sure the next command to make sure the correct Azure version is Imported how how to pass the propoer command to Import.

Import-Module -Name AzureRM -RequiredVersion? -MinimumVersion?

**Comment by moto-geek** [comment]
I found version numbers and release dates at this url and just tried installing https://www.powershellgallery.com/packages/AzureRM/6.0.1

AzureRM 3.0.0	14147 Wednesday, September 28 2016 as this was before 10-01-2016

**Install-Module -Name AzureRM -RequiredVersion 3.0.0
Import-Module -Name AzureRM -RequiredVersion 3.0.0**

Then I got this error now.. :(

The Key Vault resource for this deployment will be named:
MyWebApp-KV

Using existing authentication
Selecting subscription as default
Method 'AuthenticateAsync' in type 'Microsoft.Azure.Commands.Common.Authentication.KeyStoreApplicationCredentialProvider' from assembly 'Microsoft.Azure.Commands.Common.Authentication, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
An error has occurred in the pre-deployment orchestration setup. Please review any error messages before attempting a re-deployment.
Press any key to exit...

Maybe share what RequiredVersion I should use?

**Comment by moto-geek** [comment]
Yeah!!!, I figured it out.. 

I attempted version 5.7.0 since latest version of AzureRM 6.1? is a preview: 

Reference:
**https://github.com/Azure/azure-powershell/releases/tag/v5.7.0-April2018**

Verified using the specified AzureRM before predeployment

Name    Version Path
_AzureRM 5.7.0   C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.7.0\AzureRM.psd1_

Made it through, received "**Orchestration Complete**"

So the bug has something to do using the latest version of AzureRM when you do a "Install-Module -Name AzureRM" from the instructions, the version installed is the "preview" seen in the above errors that has the issue with the KeyVault Api. Hope this helps anyone else. 

If I have time later, I can come in and contribute or fork to help add a AzureRM Version. The ApiVersion seems to be a show stopper.  

Note: I also went through to make sure any subscription resources you had registered in your screenshot was "registered" additional to just the KeyVault. 

Thanks jomolesk for your contribution and feedback.
@jomolesk

**Comment by jomolesk** [comment]
Thank you for the feedback as well, I'll work to make sure this issue gets addressed.

**Comment by jomolesk** [comment]
PR #60 should resolve this issue. Please let me know if you continue to encounter issues.

**Comment by moto-geek** [comment]
Just re-ran with fix #60, works like a charm, thanks.
