### ISSUE TITLE
PostDeployment Error or Warning? "Enable Protection Operation failed"

### ISSUE THREAD

**Issue by moto-geek** [Azure/fedramp-iaas-webapp#66]
Here is my output. In portal under backups, I show the vm's listed with Passed precheck status. Did the error below skip over anything important? 

PS C:\_GIT\RMW\azure\blueprint\fedramp-iaas-webapp> .\postdeploy\PostDeployment.ps1
AzureRM Module exists... Importing into session.

Azure Security and Compliance Blueprint - FedRAMP Web Applications Automation - Post-Deployment Script

This script can be used for running post-deployment tasks for a multi-tier web application architecture with pre-configured security controls to help customers achieve compliance with FedRAMP requirements. See https://aka.ms/fedrampblueprint for more information.

 GENERATE VM BACKUP ITEMS

Generating Backup Items for the deployment.
The name of the Key Vault used in the deployment: VernWebApp-KV
Provide the name of the Resource Group deployed: VernWebApp

WorkloadName     Operation            Status               StartTime                 EndTime                   JobID
------------     ---------            ------               ---------                 -------                   -----
az-pdc-vm        ConfigureBackup      Completed            5/22/2018 2:36:31 PM      5/22/2018 2:37:03 PM      9f835...
az-bdc-vm        ConfigureBackup      Completed            5/22/2018 2:37:06 PM      5/22/2018 2:37:37 PM      2eb77...
az-web-vm0       ConfigureBackup      Completed            5/22/2018 2:37:41 PM      5/22/2018 2:38:12 PM      91418...
az-web-vm1       ConfigureBackup      Completed            5/22/2018 2:38:15 PM      5/22/2018 2:38:47 PM      3e542...
az-sql-vm0       ConfigureBackup      Completed            5/22/2018 2:38:50 PM      5/22/2018 2:39:21 PM      433d7...

**Enable-AzureRmRecoveryServicesBackupProtection : Enable Protection Operation failed. Error Code:
UserErrorGuestAgentStatusUnavailable. Error Message: VM agent is unable to communicate with the Azure Backup Service.**
At C:\_GIT\RMW\azure\blueprint\fedramp-iaas-webapp\postdeploy\PostDeployment.ps1:78 char:9
+         Enable-AzureRmRecoveryServicesBackupProtection -Policy $polic ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-AzureRmR...ackupProtection], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.EnableAzureRmRecoveryServicesBa
   ckupProtection

az-mgt-vm        ConfigureBackup      Completed            5/22/2018 2:41:45 PM      5/22/2018 2:42:16 PM      a05dc...
Generation of VM Backup Items completed successfully.

 CREATE INITIAL VM BACKUP

Starting Initial Backup for all VMs in the deployment
Initial Backup is starting for all VMs.

 **POST-DEPLOYMENT COMPLETE**

Post-Deployment operations for this blueprint template are complete. Please proceed with validating the deployed resources through the Azure Portal. Additional information regarding this blueprint is accessible at https://aka.ms/fedrampblueprint.

PS C:\_GIT\RMW\azure\blueprint\fedramp-iaas-webapp>

**Comment by jomolesk** [comment]
Looks like AZ-SQL-VM1 was unreachable for some reason when the script was run. You could try to re-run this script to initiate backup on that VM w/ the following edit:

`$VMList = @("AZ-SQL-VM1")`

We'll investigate why the error wasn't caught.

**Comment by moto-geek** [comment]
MY VM was offline, reran and works now.. thanks..
